name: format

on: [push, pull_request]


jobs:
    format:
        runs-on: ubuntu-latest
        container: philipdavis/dspaces-deps:v23052024 
    
        steps:
        - uses: actions/checkout@v2

        - name: clang-format
          run: scripts/format.sh cf
